name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
      - name: Unit tests
        run: python -m unittest -v
      - name: Eval sweep (optional)
        if: always()
        run: |
          python -m alpha_evolve.eval --dataset data/eval.jsonl --corpus data/corpus --iters 4 --ideas 3 --sweep "0.5,0.6,0.7,0.8,0.9" --out data/report_sweep.json
